// Claude's text: summary, recommendations, CSRD gaps, quick wins.
// If the AI call failed, shows a notice instead (the score is still valid).

const ESRS_NAMES = {
  E1: 'ESRS E1 Climate',
  E2: 'ESRS E2 Pollution',
  E3: 'ESRS E3 Water',
  E5: 'ESRS E5 Resources',
}

// Full class strings so Tailwind can find them (see MetricCard.jsx).
const PRIORITY_STYLES = {
  high: 'bg-red-100 text-red-800',
  medium: 'bg-amber-100 text-amber-800',
  low: 'bg-slate-100 text-slate-700',
}

function EsrsBadge({ standard }) {
  return (
    <span className="rounded bg-emerald-100 px-1.5 py-0.5 text-xs font-medium text-emerald-800">
      {ESRS_NAMES[standard] ?? standard}
    </span>
  )
}

function Section({ title, children }) {
  return (
    <section className="rounded-lg bg-white p-6 shadow">
      <h2 className="text-xl font-semibold">{title}</h2>
      <div className="mt-4">{children}</div>
    </section>
  )
}

function AiAnalysis({ analysis, error }) {
  if (!analysis) {
    return (
      <p role="status" className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">
        <strong>AI analysis not available.</strong> {error} The score and benchmark comparison above
        are calculated without AI and are complete.
      </p>
    )
  }

  return (
    <div className="space-y-6">
      <Section title="Summary">
        <p className="leading-relaxed">{analysis.summary}</p>
        <p className="mt-3 text-xs text-slate-500">
          Text generated by AI (Claude) from the calculated figures. Please review before using it in reports.
        </p>
      </Section>

      <Section title="Recommendations">
        <ol className="space-y-4">
          {analysis.recommendations.map((rec) => (
            <li key={rec.title} className="border-l-4 border-emerald-500 pl-4">
              <div className="flex flex-wrap items-center gap-2">
                <h3 className="font-semibold">{rec.title}</h3>
                <EsrsBadge standard={rec.esrs_standard} />
                <span className={`rounded px-1.5 py-0.5 text-xs font-medium ${PRIORITY_STYLES[rec.priority]}`}>
                  {rec.priority} priority
                </span>
              </div>
              <p className="mt-1 text-sm">{rec.description}</p>
              {rec.funding_hint && (
                <p className="mt-1 text-sm text-emerald-800">Funding: {rec.funding_hint}</p>
              )}
            </li>
          ))}
        </ol>
      </Section>

      <Section title="CSRD / ESRS gaps">
        <ul className="space-y-4">
          {analysis.csrd_gaps.map((gap) => (
            <li key={gap.gap}>
              <EsrsBadge standard={gap.esrs_standard} />
              <p className="mt-1 text-sm">
                <span className="font-medium">Gap:</span> {gap.gap}
              </p>
              <p className="text-sm">
                <span className="font-medium">Next step:</span> {gap.action}
              </p>
            </li>
          ))}
        </ul>
      </Section>

      <Section title="Quick wins (next 3 months)">
        <ul className="list-inside list-disc space-y-1 text-sm">
          {analysis.quick_wins.map((win) => (
            <li key={win}>{win}</li>
          ))}
        </ul>
      </Section>
    </div>
  )
}

export default AiAnalysis
